### ISSUE TITLE
Missing conda documentation

### ISSUE THREAD

**Issue by drjbarker** [arcdocs/arcdocs.github.io#32]
I _think_ there was some documentation on using conda on arc in the previous site. Especially some of the peculiarities around symlinking to /nobackup and touching the environments with cron. 

If memory serves John has setup an exclusion for expiring directories that have a certain path but I can't remember what this is can can't find any docs.

Unrelated to docs, I think conda on arc could be a bit more user friendly.

**Comment by jhodrien** [comment]
I agree we need a proper page on recommended python use on ARC.  We previously had:

https://arc-old.leeds.ac.uk/using-the-systems/advanced-topics/installing-applications-and-libraries-with-conda/

Something akin to this needs importing into our current site, and sooner rather than later.

I also understand your view that it would be nice if using conda on ARC was more user friendly.  I'm just not sure what the correct solution is, and am entirely open to your views on how you think it should work.

Other HPCs take the view that it's all the user's problem.  Let them install miniconda and sort it out themselves.  That I think is a marginally higher bar to get started, but has benefits later, as the user owns the whole miniconda install, and doesn't have to do anything with .conda.  I've also seen the same solution we use, but with preconfigured environments within the central install that are intended to be useful for the users, but this doesn't work brilliantly with conda either, as user and central don't really stack with conda, and you just end up cloning everything anyway.

**Comment by drjbarker** [comment]
I'm using Miniconda on arc because I don't want to have to load a module. I think just telling users to setup Miniconda themselves is ok, it's pretty damn easy. The main issue is that the user directory disk quota is so small that there is immediately a big hurdle for novices to work out how to get out of that hole.

Maybe we need to search the conda documentation and see if an environment variable can be set in the users environment by default which conda will use as a path for packages. If this is then on /nobackup then we're basically sorted. Are we particularly short of disk space for users anyway? Can the quota be tweaked?

**Comment by jhodrien** [comment]
I don't think we should be averse to users loading modules.  There's nothing stopping you adding a module load into your .bashrc if it's something you're always wanting to have loaded, although there's a lot to be said for recording this with your specific project too.

Quota currently can't be tweaked else we would have increased it.  /nobackup is problematic as we don't guarantee that a /nobackup/$USER path exists for the user, so we can't simply tell conda to use /nobackup/$USER/.conda unless it's happy to make the parent directory if it's missing, and ensure ownership is correct if it does exist.

If we stick with the current setup, we definitely need to provide a documented way to dig yourself out of the quota hole.

Module also has the downside that conda activate doesn't work, and that's not fixable without using a newer version of environment-modules, which isn't possible without doing other things...

If you're a fan of mixing pip and conda, module has the advantage that you can do:

module add anaconda
pip install --user thing

And have a fully working python3 setup with you additional module quicker than you can with miniconda.  But that's no big advantage.  I'm also not going to take the anaconda module away, so it'd be a case of documenting two alternate approaches, and choosing which one gets listed more prominently I think?

**Comment by drjbarker** [comment]
Yeah, I don't think removing the module is a good idea because some people might be using it. But the lack of activate is annoying and the fact you don't have write permissions to the default env path is surprising for novices. So I think Miniconda should be the 'prominent' solution just so people can use something they are already familiar with from their own machines.

Pip and conda should only be mixed when absolutely necessary and not in the base environment unless you want a world of pain. 

As an aside, have you used mamba? I basically use it for all my conda stuff now because some larger packages (snakemake) take tens of minutes to resolve in conda but seconds in mamba.

From my side I'm thinking to write ansible playbooks to set up user environments for my students because it takes so much 1-on-1 time setting them up each time I have a new one. Once I get round to it maybe we provide the Miniconda playbook online so supervisors who know what they're doing can provision students quickly?

**Comment by jhodrien** [comment]
I think this should be closed, as there is a page on using [Anaconda](https://arcdocs.leeds.ac.uk/software/compilers/anaconda.html)

Slightly confusingly this comes under compilers, which is where anaconda has been categorised within the modules system.

As to how conda should be presented on the HPC, I've seen three HPCs who have done it three ways.  Present as a module, but have your home directory stored on Lustre appears in many ways to be the best solution as far as conda is concerned.
